[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"

[docs]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[project]
name = "MultimodalMaps"
authors = ["Carter Hinsley <carterhinsley@gmail.com>"]
description = "Symbolic scans of multimodal maps of an interval"
version = "0.1.0"
