[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[docs]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[project]
name = "MultimodalMaps"
authors = ["Carter Hinsley <carterhinsley@gmail.com>"]
description = "Symbolic scans of multimodal maps of an interval"
version = "0.1.0"
